### PR TITLE
RsIskraMeter: Report error on consistent meter communication failure

### PR DESCRIPTION
**Pull request by wku12**
## Describe your changes
Now when we have communication errors with RsIskraMeter we will report errors. To have it working we have to bump everest-framework, so please do not look at those changes for now.
## Checklist before requesting a review
- [ X] I have performed a self-review of my code
- [X ] I have made corresponding changes to the documentation
- [X ] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by SirVer** [comment]
@wku12 can you please remove the reviewers until this is ready for review?

**Comment by Pietfried** [comment]
> Member

I think developers listed in the CODEOWNERS are automatically requested and cannot be removed afterwards but as long as PRs are in draft, we know its not yet ready for review.

**Comment by wku12** [comment]
@SirVer @Pietfried It's ready for review now - I rebased with the everest-framework bump you have done

**Review by dorezyuk — APPROVED** [review]

**Review by SirVer — APPROVED** [review]

**Comment by SirVer** [comment]
@hikinggrass @Pietfried @corneliusclaussen I am not sure why you are selected as reviewers, since this does not touch on anything besides Rust stuff, but could we get a rubberstamp to satisfy GitHub, please?

**Review by hikinggrass — APPROVED** [review]

**Review by corneliusclaussen — APPROVED** [review]

**Pull request merged**
