### PR TITLE
Bump version of used github action run-clang-format to v1.1.0

### PR DESCRIPTION
**Pull request by andistorm**
## Describe your changes
- Bump version of used github action run-clang-format to v1.1.0
## Issue ticket number and link
https://github.com/EVerest/everest-ci/issues/11
## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Review by SebaLukas — APPROVED** [review]
:+1: at last

**Review by Pietfried — APPROVED** [review]

**Comment by andistorm** [comment]
Can't merge seems to need approval from all reviewers, shouldn't be only one approval necessary @Pietfried ?

**Comment by barsnick** [comment]
> shouldn't be only one approval necessary

Probably one of each set of code owners for each file affected is required. The reformatting touched quite a lot of modules, so all their approvals might be necessary.

https://github.com/EVerest/everest-core/blob/f1ad5ccf33de21e7cb507f6e421bfd3930534630/.github/CODEOWNERS#L18-L33

I guess YetiDriver code owners are not covered yet.

**Comment by andistorm** [comment]
@barsnick that makes sense, thank you for explaining.

**Review by hikinggrass — APPROVED** [review]

**Pull request merged**
